# Generated by Django 3.0.4 on 2020-03-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='image',
            new_name='image_url',
        ),
    ]
