# Generated by Django 3.0.4 on 2020-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200306_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
