# Generated by Django 3.0.4 on 2020-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200306_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
