# Generated by Django 3.0.4 on 2020-03-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200306_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
